import type { Cliente, ConfigEmpresa, Empleado, EstadoEmpresa, FacturaSimulada, MovimientoContable, ProductoSintetico, Proveedor, VentaSintetica } from './tipos.ts';
export class EmpresaSimuladaError extends Error {}
class Aleatorio { private estado: number; constructor(seed: number) { this.estado = seed >>> 0; } siguiente(): number { this.estado = (1664525 * this.estado + 1013904223) >>> 0; return this.estado / 4294967296; } }
const dinero = (valor: number): number => Math.round((valor + Number.EPSILON) * 100) / 100;
export class EmpresaSimulada {
  readonly clientes: Cliente[]; readonly proveedores: Proveedor[]; readonly empleados: Empleado[]; readonly movimientos: MovimientoContable[] = []; readonly facturas: FacturaSimulada[] = []; readonly productos: Map<string, ProductoSintetico>;
  readonly config: ConfigEmpresa;
  private caja: number; private porCobrar = 0; private porPagar = 0; private ventas = 0; private costos = 0; private nomina = 0; private secuencia = 0; private azar: Aleatorio;
  constructor(config: ConfigEmpresa) { this.config = config; if (!Number.isInteger(config.seed) || config.capitalInicial <= 0 || !config.nombre || !config.moneda || !config.productos.length) throw new EmpresaSimuladaError('Configuración sintética inválida.'); this.azar = new Aleatorio(config.seed); this.caja = config.capitalInicial; this.productos = new Map(config.productos.map((p) => [p.id, { ...p }])); if ([...this.productos.values()].some((p) => !p.id || p.precio <= 0 || p.costo <= 0 || p.stockInicial < 0 || p.stockMinimo < 0)) throw new EmpresaSimuladaError('Producto sintético inválido.'); this.clientes = Array.from({ length: 3 }, (_, i) => ({ id: `cli-${i + 1}`, nombre: `Cliente Sintético ${i + 1}`, recurrente: this.azar.siguiente() > .3 })); this.proveedores = Array.from({ length: 2 }, (_, i) => ({ id: `prov-${i + 1}`, nombre: `Proveedor Sintético ${i + 1}`, leadTimeDias: 2 + i, fiabilidad: .8 + i / 10, minimo: 1 })); this.empleados = Array.from({ length: config.empleados }, (_, i) => ({ id: `emp-${i + 1}`, nombre: `Empleado Sintético ${i + 1}`, salarioPeriodo: 1000 + i * 100 })); this.asentar('capital inicial simulado', 'Caja', 'Capital', config.capitalInicial, 'inicio'); }
  private id(prefijo: string): string { this.secuencia += 1; return `${prefijo}-${this.secuencia}`; }
  private asentar(concepto: string, debe: string, haber: string, importe: number, referencia: string): void { importe = dinero(importe); if (!Number.isFinite(importe) || importe <= 0 || !debe || !haber || debe === haber) throw new EmpresaSimuladaError('Asiento contable simulado desbalanceado.'); this.movimientos.push({ id: this.id('mov'), timestampSimulado: `T${this.secuencia}`, concepto, cuentaDebe: debe, cuentaHaber: haber, importe, referencia, origen: 'simulacion', metadata: { simulated: 1 } }); }
  vender(productoId: string, cantidad: number, clienteId = this.clientes[0]!.id, credito = false): VentaSintetica { const p = this.productos.get(productoId); if (!p || !this.clientes.some((c) => c.id === clienteId) || !Number.isInteger(cantidad) || cantidad <= 0) throw new EmpresaSimuladaError('Venta simulada inválida.'); if (p.stockInicial < cantidad) throw new EmpresaSimuladaError('Stock insuficiente: nunca se permite inventario negativo.'); const total = dinero(p.precio * cantidad), costo = dinero(p.costo * cantidad); p.stockInicial -= cantidad; const factura = { id: this.id('fac'), clienteId, total, estado: credito ? 'pendiente' as const : 'pagada' as const }; this.facturas.push(factura); this.ventas = dinero(this.ventas + total); this.costos = dinero(this.costos + costo); if (credito) this.porCobrar = dinero(this.porCobrar + total); else this.caja = dinero(this.caja + total); this.asentar('venta simulada', credito ? 'Cuentas por cobrar' : 'Caja', 'Ventas', total, factura.id); this.asentar('costo de venta simulado', 'Costo de ventas', 'Inventario', costo, factura.id); return { id: this.id('venta'), productoId, cantidad, total, costo, factura }; }
  comprar(productoId: string, cantidad: number, proveedorId = this.proveedores[0]!.id, credito = true): void { const p = this.productos.get(productoId); if (!p || !this.proveedores.some((v) => v.id === proveedorId) || !Number.isInteger(cantidad) || cantidad <= 0) throw new EmpresaSimuladaError('Compra simulada inválida.'); const total = dinero(p.costo * cantidad); if (!credito && this.caja < total) throw new EmpresaSimuladaError('Caja simulada insuficiente.'); p.stockInicial += cantidad; if (credito) this.porPagar = dinero(this.porPagar + total); else this.caja = dinero(this.caja - total); this.asentar('compra simulada', 'Inventario', credito ? 'Cuentas por pagar' : 'Caja', total, proveedorId); }
  pagarFacturaSimulada(id: string): void { const f = this.facturas.find((x) => x.id === id); if (!f || f.estado !== 'pendiente') throw new EmpresaSimuladaError('Factura simulada no pagable.'); f.estado = 'pagada'; this.porCobrar -= f.total; this.caja += f.total; this.asentar('cobro simulado', 'Caja', 'Cuentas por cobrar', f.total, f.id); }
  pagarNominaSimulada(): number { const total = this.empleados.reduce((s, e) => s + e.salarioPeriodo, 0); if (total > this.caja) throw new EmpresaSimuladaError('Caja simulada insuficiente para nómina.'); this.caja -= total; this.nomina += total; if (total) this.asentar('NominaSimulada', 'Gasto nómina', 'Caja', total, 'nomina'); return total; }
  bancoSimulado(accion: 'depositarSimulado' | 'retirarSimulado' | 'transferirInternoSimulado', importe: number): void { if (!Number.isFinite(importe) || importe <= 0) throw new EmpresaSimuladaError('Movimiento bancario simulado inválido.'); if (accion === 'retirarSimulado' && this.caja < importe) throw new EmpresaSimuladaError('Caja simulada insuficiente.'); if (accion === 'depositarSimulado') this.caja += importe; if (accion === 'retirarSimulado') this.caja -= importe; this.asentar(accion, accion === 'depositarSimulado' ? 'Caja' : 'Banco simulado', accion === 'depositarSimulado' ? 'Banco simulado' : 'Caja', importe, 'banco-interno'); }
  estado(): EstadoEmpresa { const inventarioValorizado = dinero([...this.productos.values()].reduce((s, p) => s + p.stockInicial * p.costo, 0)); return { caja: dinero(this.caja), cuentasPorCobrar: dinero(this.porCobrar), cuentasPorPagar: dinero(this.porPagar), inventarioValorizado, ventas: dinero(this.ventas), costos: dinero(this.costos), gastosNomina: dinero(this.nomina), utilidad: dinero(this.ventas - this.costos - this.nomina) }; }
  estadosFinancierosSimulados(): { balance: Record<string, number>; resultados: Record<string, number>; flujoCaja: number; cuentasPorCobrar: number; cuentasPorPagar: number; inventario: number; nomina: number; etiqueta: 'SIMULACIÓN' } { const e = this.estado(); return { balance: { caja: e.caja, cuentasPorCobrar: e.cuentasPorCobrar, inventario: e.inventarioValorizado, cuentasPorPagar: e.cuentasPorPagar }, resultados: { ventas: e.ventas, costos: e.costos, nomina: e.gastosNomina, utilidad: e.utilidad }, flujoCaja: e.caja - this.config.capitalInicial, cuentasPorCobrar: e.cuentasPorCobrar, cuentasPorPagar: e.cuentasPorPagar, inventario: e.inventarioValorizado, nomina: e.gastosNomina, etiqueta: 'SIMULACIÓN' }; }
  auditarLedger(): boolean { return this.movimientos.every((m) => m.importe > 0 && m.cuentaDebe !== m.cuentaHaber && m.origen === 'simulacion'); }
}
export function crearEmpresa(config: ConfigEmpresa): EmpresaSimulada { return new EmpresaSimulada(config); }
