import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs'; import { dirname } from 'node:path';
export type EstadoExperienciaEmpresa = 'OBSERVADA' | 'EVALUADA' | 'CANDIDATA' | 'VALIDADA' | 'RECHAZADA';
export interface ExperienciaEmpresa { id: number; escenario: string; seed: number; contexto: string; hipotesis: string; decision: string; metricasAntes: Record<string, number>; metricasDespues: Record<string, number>; resultadoFinanciero: number; reglasCumplidas: string[]; reglasRotas: string[]; eventosExternos: string[]; evidencia: string; evaluacion: string; confianza: number; estado: EstadoExperienciaEmpresa; version: number; createdAt: string; }
export interface PoliticaValidacionEmpresa { minEjecuciones: number; minSeeds: number; minEscenarios: number; minConfianza: number; }
const politicaPorDefecto: PoliticaValidacionEmpresa = { minEjecuciones: 3, minSeeds: 2, minEscenarios: 2, minConfianza: .7 };
const esquema = `CREATE TABLE IF NOT EXISTS experiencias_empresa (id INTEGER PRIMARY KEY AUTOINCREMENT, datos TEXT NOT NULL, estado TEXT NOT NULL); CREATE TABLE IF NOT EXISTS resumenes_empresa (clave TEXT NOT NULL, version INTEGER NOT NULL, texto TEXT NOT NULL, PRIMARY KEY(clave, version));`;
export class MemoriaEmpresarial {
  private db: DatabaseSync; readonly politica: PoliticaValidacionEmpresa;
  constructor(ruta = ':memory:', politica: Partial<PoliticaValidacionEmpresa> = {}) { if (ruta !== ':memory:') mkdirSync(dirname(ruta), { recursive: true }); this.db = new DatabaseSync(ruta); this.db.exec(esquema); this.politica = { ...politicaPorDefecto, ...politica }; }
  cerrar(): void { this.db.close(); }
  observar(nueva: Omit<ExperienciaEmpresa, 'id' | 'estado' | 'version' | 'createdAt'>): ExperienciaEmpresa { if (!nueva.escenario || !Number.isInteger(nueva.seed) || !nueva.hipotesis || !nueva.decision || nueva.reglasRotas.length || nueva.confianza < 0 || nueva.confianza > 1) { if (nueva.reglasRotas.length) return this.guardar({ ...nueva, estado: 'RECHAZADA', evaluacion: 'Regla crítica rota.' }); throw new Error('Experiencia empresarial inválida.'); } return this.guardar({ ...nueva, estado: 'OBSERVADA' }); }
  private guardar(nueva: Omit<ExperienciaEmpresa, 'id' | 'version' | 'createdAt'>): ExperienciaEmpresa { if (nueva.estado === 'VALIDADA') throw new Error('Una experiencia empresarial no puede guardarse directamente como VALIDADA.'); const base = { ...nueva, version: 1, createdAt: new Date().toISOString() }; const r = this.db.prepare('INSERT INTO experiencias_empresa (datos, estado) VALUES (?, ?)').run(JSON.stringify(base), base.estado); return { id: Number(r.lastInsertRowid), ...base }; }
  porId(id: number): ExperienciaEmpresa | null { const f = this.db.prepare('SELECT id, datos FROM experiencias_empresa WHERE id=?').get(id) as { id: number; datos: string } | undefined; return f ? { id: Number(f.id), ...JSON.parse(f.datos) } : null; }
  listar(): ExperienciaEmpresa[] { return (this.db.prepare('SELECT id, datos FROM experiencias_empresa ORDER BY id').all() as { id: number; datos: string }[]).map((f) => ({ id: Number(f.id), ...JSON.parse(f.datos) })); }
  evaluar(id: number, evaluacion: string, candidata = false): ExperienciaEmpresa { const e = this.porId(id); if (!e || e.estado === 'RECHAZADA') throw new Error('Experiencia no evaluable.'); return this.actualizar(e, { evaluacion, estado: candidata ? 'CANDIDATA' : 'EVALUADA' }); }
  validar(ids: number[]): ExperienciaEmpresa[] { const seleccion = ids.map((id) => this.porId(id)).filter((x): x is ExperienciaEmpresa => x !== null); const p = this.politica; if (seleccion.length < p.minEjecuciones || new Set(seleccion.map((e) => e.seed)).size < p.minSeeds || new Set(seleccion.map((e) => e.escenario)).size < p.minEscenarios || seleccion.some((e) => e.reglasRotas.length || e.confianza < p.minConfianza || !['EVALUADA', 'CANDIDATA'].includes(e.estado))) throw new Error('Evidencia insuficiente para validar experiencia empresarial.'); return seleccion.map((e) => this.actualizar(e, { estado: 'VALIDADA', evaluacion: `${e.evaluacion} Validada por evidencia múltiple.` })); }
  private actualizar(e: ExperienciaEmpresa, cambio: Partial<ExperienciaEmpresa>): ExperienciaEmpresa { const nuevo = { ...e, ...cambio, version: e.version + 1 }; this.db.prepare('UPDATE experiencias_empresa SET datos=?, estado=? WHERE id=?').run(JSON.stringify({ ...nuevo, id: undefined }), nuevo.estado, e.id); return nuevo; }
  guardarResumen(clave: string, texto: string): number { const ultimo = this.db.prepare('SELECT MAX(version) AS v FROM resumenes_empresa WHERE clave=?').get(clave) as { v: number | null }; const version = Number(ultimo.v ?? 0) + 1; this.db.prepare('INSERT INTO resumenes_empresa (clave,version,texto) VALUES (?,?,?)').run(clave, version, texto); return version; }
  resumenes(clave: string): { version: number; texto: string }[] { return this.db.prepare('SELECT version,texto FROM resumenes_empresa WHERE clave=? ORDER BY version').all(clave) as { version: number; texto: string }[]; }
  comparar(ids: number[], pesos: Record<'beneficio' | 'liquidez' | 'riesgo' | 'cumplimiento', number>): { id: number; puntuacion: number; pesos: typeof pesos }[] { if (Object.values(pesos).some((x) => x < 0)) throw new Error('Pesos inválidos.'); return ids.map((id) => this.porId(id)).filter((x): x is ExperienciaEmpresa => !!x).map((e) => ({ id: e.id, puntuacion: e.resultadoFinanciero * pesos.beneficio + (e.metricasDespues.caja ?? 0) * pesos.liquidez - e.reglasRotas.length * pesos.riesgo + e.reglasCumplidas.length * pesos.cumplimiento, pesos: { ...pesos } })).sort((a, b) => b.puntuacion - a.puntuacion); }
  resumen(): Record<EstadoExperienciaEmpresa, number> { const r: Record<EstadoExperienciaEmpresa, number> = { OBSERVADA: 0, EVALUADA: 0, CANDIDATA: 0, VALIDADA: 0, RECHAZADA: 0 }; this.listar().forEach((e) => r[e.estado]++); return r; }
}
