import test from 'node:test'; import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import { AtlasLocalApi } from '../src/api-local/servidor.ts';
const leer = (f: string) => readFileSync(new URL(`../src/panel-vortice/${f}`, import.meta.url), 'utf8');
const html = leer('index.html'), css = leer('app.css') + leer('premium.css'), js = leer('app.js');
const dashboard = () => ({ system: { version: '0.1.0', estado: 'OK', simulated: true }, vortice: { estado: 'local', modo: 'ahorro', cola: 0, decisiones: [] }, providers: { Ollama: 'unavailable', Claude: 'disabled', OpenAI: 'disabled' }, trading: { mt5Real: 'PENDIENTE' }, business: { simulated: true }, simulations: { totalWorkers: 0, running: 0, paused: 0, completed: 0, failed: 0, workers: [] }, memory: { empresa: {}, simulated: true }, audit: { eventos: [] }, resources: { origen: 'UNAVAILABLE', cpu: null, ram: null, workers: 0 }, alerts: [] }) as any;
const secciones = ['inicio', 'empresa', 'finanzas', 'ventas', 'inventario', 'nomina', 'facturacion', 'clientes', 'proveedores', 'simulacion', 'trading', 'video', 'agentes', 'vortice', 'reportes'];

test('R sidebar ofrece las 16 secciones del Business OS', () => {
  for (const s of secciones) assert.ok(html.includes(`data-nav="${s}"`), s);
  for (const etiqueta of ['Inicio', 'Empresa', 'Finanzas', 'Ventas', 'Inventario', 'Nómina', 'Facturación', 'Clientes', 'Proveedores', 'Simulación', 'Trading', 'Análisis de Video', 'Agentes IA', 'El Vórtice', 'Reportes', 'Configuración']) assert.ok(html.includes(`<span>${etiqueta}</span>`), etiqueta);
});
test('R cada sección del sidebar tiene vista y al menos un panel', () => { for (const s of secciones) { assert.ok(js.includes(`${s}:[`), `vista ${s}`); assert.ok(new RegExp(`data-views="[^"]*\\b${s}\\b`).test(html), `panel ${s}`); } });
test('R topbar ofrece cinco modos, búsqueda, alertas, estado y SIMULATED', () => {
  for (const m of ['simple', 'executive', 'advanced', 'visual', 'custom']) assert.ok(html.includes(`data-mode="${m}"`), m);
  for (const t of ['Simple', 'Ejecutivo', 'Avanzado', 'Visual', 'Personalizado']) assert.ok(html.includes(`>${t}</button>`), t);
  assert.ok(html.includes('id="search"') && html.includes('id="alert-count"') && html.includes('id="system"') && html.includes('class="simulated"'));
});
test('R núcleo muestra los seis canales conectados', () => { for (const c of ['texto', 'voz', 'imagenes', 'video', 'datos', 'simulacion']) { assert.ok(html.includes(`data-channel="${c}"`) && html.includes(`data-link="${c}"`) && html.includes(`id="ch-${c}"`), c); } });
test('R canales sin fuente en la API quedan UNAVAILABLE, no inventados', () => assert.ok(js.includes('texto:undefined,voz:undefined,imagenes:undefined,video:undefined')));
test('R núcleo mantiene estado, policy, Supervisor, queue, decisiones y última acción', () => { for (const id of ['core-estado', 'core-policy', 'core-supervisor', 'core-queue', 'core-decisions', 'core-last-action']) assert.ok(html.includes(`id="${id}"`), id); assert.ok(js.includes("['core-supervisor',undefined]")); });
test('R proveedores IA sin porcentajes de cuota ni API keys', () => { assert.ok(html.includes('data-slot="providers"') && js.includes("'cuota · UNAVAILABLE'")); assert.equal(/apiKey|api_key|%\s*cuota|cuota\s*\d/i.test(html + js), false); });
test('R trading solo muestra estado: MT5 Real PENDING y sin botones de operación', () => { assert.ok(js.includes("v==='PENDIENTE'?'PENDING'")); for (const k of ['Trading Lab', 'Backtester', 'OOS', 'Walk-forward', 'Paper Trading', 'MT5 Bridge Local', 'MT5 Real']) assert.ok(js.includes(`['${k}',`), k); assert.equal(/fetch\([^)]*method/i.test(js), false); assert.equal(/\/api\/(trading|mt5)/.test(js), false); });
test('R empresa muestra los ocho KPIs pedidos y Stockouts UNAVAILABLE', () => { for (const k of ['Cash', 'Revenue', 'Expenses', 'Profit', 'Inventory', 'Employees', 'Suppliers', 'Stockouts']) assert.ok(js.includes(`'${k}`), k); assert.ok(js.includes("['stockouts','Stockouts',()=>undefined")); });
test('R módulos premium existen: agentes, simulación, memoria, alertas y video', () => { for (const s of ['agents', 'simulation', 'memory', 'alerts', 'video', 'workers', 'audit']) assert.ok(html.includes(`data-slot="${s}"`), s); });
test('R gráficos locales ligeros sin librerías ni createElementNS', () => { assert.ok(html.includes('<template id="kpi">') && js.includes('sparkPoints')); assert.equal(js.includes('createElementNS'), false); assert.equal(/<script[^>]+src="(?!\/panel-vortice\/)/.test(html), false); });
test('R configuración visual vive en un drawer y conserva temas, acentos y presets', () => { const drawer = html.slice(html.indexOf('<dialog id="settings"'), html.indexOf('</dialog>')); assert.ok(drawer.includes('id="appearance"') && drawer.includes('appearance-reset')); for (const c of ['data-theme-choice="dark"', 'data-theme-choice="light"', 'data-theme-choice="auto"', 'data-accent-choice="orange"', 'data-style-choice="industrial-dark"']) assert.ok(drawer.includes(c), c); });
test('R modo personalizado persiste preferencias locales', () => { assert.ok(js.includes('vortice.customModules') && js.includes('vortice.customCore')); assert.ok(css.includes('#app[data-view=inicio][data-mode=custom] .custom-hidden')); });
test('R modo visual agranda el núcleo', () => assert.ok(css.includes('#app[data-mode=visual] #vortex-core') && css.includes('#app[data-mode=visual] .vortex-art')));
test('R responsive: tablet adapta grid y móvil colapsa sidebar', () => { assert.ok(css.includes('@media(max-width:1180px)') && css.includes('@media(max-width:760px)')); assert.ok(css.includes('body.nav-open .sidebar') && html.includes('id="menu-toggle"')); });
test('R el panel no escribe HTML dinámico ni usa eval o red externa', () => { assert.equal(/innerHTML|outerHTML|insertAdjacentHTML|document\.write|new Function|eval\(/.test(js), false); assert.equal(/https?:\/\//.test(html + css + js), false); });
test('R el servidor sigue sirviendo los assets del panel en loopback', async () => { const api = new AtlasLocalApi({ dashboard }, { port: 0 }); await api.start(); try { const base = `http://127.0.0.1:${api.address().port}`; for (const p of ['/panel-vortice/', '/panel-vortice/app.css', '/panel-vortice/premium.css', '/panel-vortice/app.js']) assert.equal((await fetch(base + p)).status, 200, p); const d = (await (await fetch(base + '/api/dashboard')).json()).data; assert.equal(d.trading.mt5Real, 'PENDIENTE'); } finally { await api.close(); } });
