import type { EmpresaSimulada } from '../empresa-simulator/empresa.ts'; import type { MemoriaEmpresarial } from '../empresa-simulator/memoria.ts'; import type { SimulationScheduler } from '../simulaciones/orquestador.ts';
export type AlertaPanel = { nivel: 'INFO' | 'WARNING' | 'CRITICAL'; codigo: string; mensaje: string; simulated: boolean };
export interface AtlasDashboardState { system: { version: string; estado: 'OK'; simulated: boolean }; vortice: { estado: string; modo: string; cola: number; decisiones: string[] }; providers: Record<string, 'disabled' | 'unavailable' | 'configured'>; trading: { tradingLab: string; backtester: string; oos: string; walkForward: string; paper: string; mt5BridgeLocal: 'IMPLEMENTADO'; mt5Real: 'PENDIENTE' }; business: { nombre: string; scenario: string; seed: number; caja: number; ventas: number; gastos: number; resultado: number; inventario: number; empleados: number; proveedores: number; cuentasCobrar: number; cuentasPagar: number; simulated: true }; simulations: ReturnType<SimulationScheduler['resumen']> & { workers: ReturnType<SimulationScheduler['lista']> }; memory: { empresa: Record<string, number>; simulated: true }; audit: { eventos: { categoria: string; resultado: string; timestamp: string }[] }; resources: { origen: 'UNAVAILABLE'; cpu: null; ram: null; workers: number }; alerts: AlertaPanel[]; }
export class EstadoPanelAtlas {
  private empresa: EmpresaSimulada; private simulaciones: SimulationScheduler; private memoria: MemoriaEmpresarial;
  constructor(empresa: EmpresaSimulada, simulaciones: SimulationScheduler, memoria: MemoriaEmpresarial) { this.empresa = empresa; this.simulaciones = simulaciones; this.memoria = memoria; }
  obtener(): AtlasDashboardState { const e = this.empresa.estado(); return { system: { version: '0.1.0', estado: 'OK', simulated: true }, vortice: { estado: 'local', modo: 'ahorro', cola: 0, decisiones: [] }, providers: { Ollama: 'unavailable', Claude: 'disabled', OpenAI: 'disabled', Gemini: 'unavailable' }, trading: { tradingLab: 'IMPLEMENTADO', backtester: 'IMPLEMENTADO', oos: 'IMPLEMENTADO', walkForward: 'IMPLEMENTADO', paper: 'IMPLEMENTADO', mt5BridgeLocal: 'IMPLEMENTADO', mt5Real: 'PENDIENTE' }, business: { nombre: this.empresa.config.nombre, scenario: 'NORMAL', seed: this.empresa.config.seed, caja: e.caja, ventas: e.ventas, gastos: e.gastosNomina, resultado: e.utilidad, inventario: e.inventarioValorizado, empleados: this.empresa.empleados.length, proveedores: this.empresa.proveedores.length, cuentasCobrar: e.cuentasPorCobrar, cuentasPagar: e.cuentasPorPagar, simulated: true }, simulations: { ...this.simulaciones.resumen(), workers: this.simulaciones.lista() }, memory: { empresa: this.memoria.resumen(), simulated: true }, audit: { eventos: this.simulaciones.historialEventos().slice(-10).map((x) => ({ categoria: x.tipo, resultado: x.worker.estado, timestamp: x.timestamp })) }, resources: { origen: 'UNAVAILABLE', cpu: null, ram: null, workers: this.simulaciones.resumen().running }, alerts: [{ nivel: 'INFO', codigo: 'mt5_pending', mensaje: 'MT5 real pendiente de validación DEMO.', simulated: false }] }; }
}
export interface CanalEstadoPanel { suscribir(oyente: (estado: AtlasDashboardState) => void): () => void; }
export class PollingPanelLocal implements CanalEstadoPanel { private panel: EstadoPanelAtlas; constructor(panel: EstadoPanelAtlas) { this.panel = panel; } suscribir(oyente: (estado: AtlasDashboardState) => void): () => void { oyente(this.panel.obtener()); return () => {}; } }
