import { createServer, type IncomingMessage, type Server, type ServerResponse } from 'node:http';
import { randomUUID } from 'node:crypto';
import type { AtlasDashboardState } from '../panel/contratos.ts';

export interface AtlasApiConfig { host?: string; port?: number; maxBodyBytes?: number; }
export interface AtlasApiDependencies { dashboard: () => AtlasDashboardState; simulations?: () => unknown; campaigns?: () => unknown; experiments?: () => unknown; memory?: () => unknown; vortice?: () => unknown; alerts?: () => unknown; mutate?: (kind: string, id: string, body: Record<string, unknown>) => unknown; }
const MAX = 64 * 1024;
function seguroHost(host: string): '127.0.0.1' { if (host === '0.0.0.0' || host === '::' || host === '[::]') throw new Error('El bind público está prohibido.'); if (host !== '127.0.0.1') throw new Error('Solo se permite 127.0.0.1.'); return host; }
function enviar(res: ServerResponse, status: number, value: unknown): void { res.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'no-referrer' }); res.end(JSON.stringify(value)); }
function error(res: ServerResponse, status: number, code: string): void { enviar(res, status, { ok: false, error: { code, message: code.replaceAll('_', ' '), correlationId: randomUUID() } }); }
function peligroso(value: unknown): boolean { return !!value && typeof value === 'object' && Object.keys(value as Record<string, unknown>).some((k) => ['__proto__', 'prototype', 'constructor'].includes(k) || peligroso((value as Record<string, unknown>)[k])); }
function dto(body: Record<string, unknown>, permitidos: readonly string[]): Record<string, unknown> { if (Object.keys(body).some((k) => !permitidos.includes(k))) throw new Error('BAD_REQUEST'); return Object.fromEntries(Object.entries(body).filter(([k]) => permitidos.includes(k))); }
async function body(req: IncomingMessage, max: number): Promise<Record<string, unknown>> { if (!String(req.headers['content-type'] ?? '').startsWith('application/json')) throw new Error('UNSUPPORTED_MEDIA_TYPE'); let size = 0, raw = ''; for await (const c of req) { size += Buffer.byteLength(c); if (size > max) throw new Error('PAYLOAD_TOO_LARGE'); raw += c; } try { const parsed = raw ? JSON.parse(raw) : {}; if (!parsed || typeof parsed !== 'object' || peligroso(parsed)) throw new Error('BAD_REQUEST'); return parsed as Record<string, unknown>; } catch (e) { if (e instanceof Error && ['PAYLOAD_TOO_LARGE', 'BAD_REQUEST'].includes(e.message)) throw e; throw new Error('BAD_REQUEST'); } }
export class AtlasLocalApi {
  private server: Server | null = null; private config: Required<AtlasApiConfig>;
  private readonly deps: AtlasApiDependencies;
  constructor(deps: AtlasApiDependencies, config: AtlasApiConfig = {}) { this.deps = deps; this.config = { host: seguroHost(config.host ?? '127.0.0.1'), port: config.port ?? 0, maxBodyBytes: config.maxBodyBytes ?? MAX }; }
  async start(): Promise<void> { if (this.server) return; const server = createServer((q, s) => { void this.handle(q, s); }); this.server = server; await new Promise<void>((resolve, reject) => { const error = (e: Error) => { server.off('listening', listening); this.server = null; reject(e); }, listening = () => { server.off('error', error); resolve(); }; server.once('error', error); server.once('listening', listening); server.listen(this.config.port, this.config.host); }); }
  address(): { host: string; port: number } { const a = this.server?.address(); if (!a || typeof a === 'string') throw new Error('Servidor no iniciado.'); return { host: a.address, port: a.port }; }
  async close(): Promise<void> { if (!this.server) return; const s = this.server; this.server = null; await new Promise<void>((resolve, reject) => s.close((e) => e ? reject(e) : resolve())); }
  private async handle(req: IncomingMessage, res: ServerResponse): Promise<void> { const url = new URL(req.url ?? '/', 'http://127.0.0.1'); const path = url.pathname, method = req.method ?? 'GET'; const dash = () => this.deps.dashboard(); if (method === 'GET') { const map: Record<string, () => unknown> = { '/api/status': () => ({ ok: true, atlas: dash().system, offline: true, mt5Real: 'PENDIENTE' }), '/api/dashboard': dash, '/api/simulations': () => this.deps.simulations?.() ?? dash().simulations, '/api/business': () => ({ ...dash().business, simulated: true }), '/api/business/campaigns': () => this.deps.campaigns?.() ?? [], '/api/business/experiments': () => this.deps.experiments?.() ?? [], '/api/trading': () => dash().trading, '/api/memory': () => this.deps.memory?.() ?? dash().memory, '/api/alerts': () => this.deps.alerts?.() ?? dash().alerts, '/api/vortice': () => this.deps.vortice?.() ?? dash().vortice }; const f = map[path]; if (!f) return error(res, 404, 'NOT_FOUND'); return enviar(res, 200, { ok: true, data: f() }); }
    if (method !== 'POST') return error(res, 405, 'METHOD_NOT_ALLOWED'); const origin = req.headers.origin, host = String(req.headers.host ?? ''); if (origin && !/^http:\/\/(127\.0\.0\.1|localhost)(?::\d+)?$/.test(origin)) return error(res, 403, 'FORBIDDEN_ORIGIN'); if (!/^(127\.0\.0\.1|localhost)(?::\d+)?$/.test(host)) return error(res, 403, 'FORBIDDEN_HOST'); const match = path.match(/^\/api\/(business\/campaigns|simulations)\/([^/]+)\/(pause|resume|stop)$/); const create = path === '/api/business/campaigns' ? { kind: 'business/campaigns', fields: ['nombre', 'version', 'scenarioSet', 'seedSet', 'duracionVirtual', 'metricasObjetivo'] } : path === '/api/business/experiments' ? { kind: 'business/experiments', fields: ['name', 'version', 'trainingSeeds', 'validationSeeds', 'holdoutSeeds', 'trainingScenarios', 'validationScenarios', 'holdoutScenarios', 'duration', 'metrics', 'weights'] } : null; if (!match && !create) return error(res, 404, 'NOT_FOUND'); let data: Record<string, unknown>; try { data = dto(await body(req, this.config.maxBodyBytes), match ? [] : create!.fields); } catch (e) { const code = e instanceof Error ? e.message : 'BAD_REQUEST'; return error(res, code === 'PAYLOAD_TOO_LARGE' ? 413 : code === 'UNSUPPORTED_MEDIA_TYPE' ? 415 : 400, code); } try { const kind = match ? `${match[1]}:${match[3]}` : create!.kind, id = match?.[2] ?? ''; const result = this.deps.mutate?.(kind, id, data) ?? { simulated: true }; return enviar(res, 200, { ok: true, data: result }); } catch { return error(res, 409, 'CONFLICT'); }
  }
}
