/** Experimentos empresariales reproducibles y exclusivamente simulados. */
import { crearEmpresa, EmpresaSimulada } from '../empresa-simulator/empresa.ts';
import type { ConfigEmpresa } from '../empresa-simulator/tipos.ts';
import { observarEmpresa, procesarPropuesta, type BusinessPolicySegura } from './cerebro.ts';
import { MemoriaEmpresarial } from '../empresa-simulator/memoria.ts';

export type ParticionExperimento = 'TRAINING' | 'VALIDATION' | 'HOLDOUT';
export type DireccionMetrica = 'MAXIMIZE' | 'MINIMIZE';
export type EstadoExperimento = 'PENDING' | 'RUNNING' | 'PAUSED' | 'COMPLETED' | 'FAILED' | 'STOPPED';
export interface MetricaExperimento { name: string; value: number; direction: DireccionMetrica; }
export interface ConfigExperimento { experimentId: string; version: string; name: string; policies: BusinessPolicySegura[]; trainingSeeds: number[]; validationSeeds: number[]; holdoutSeeds: number[]; trainingScenarios: string[]; validationScenarios: string[]; holdoutScenarios: string[]; duration: number; configEmpresa: ConfigEmpresa; metrics?: string[]; constraints?: Record<string, unknown>; createdAt: string; strictPartitioning?: boolean; weights?: Record<string, number>; }
export interface ExperimentRun { experimentId: string; partition: ParticionExperimento; policyId: string; policyVersion: string; seed: number; scenario: string; initialCheckpointId: string; duration: number; status: 'COMPLETED' | 'FAILED'; metrics: MetricaExperimento[]; violations: string[]; evaluation: string; simulated: true; error?: string; }
export interface Estadisticas { count: number; mean: number | null; median: number | null; min: number | null; max: number | null; standardDeviation: number | null; }
export interface ResumenParticion { partition: ParticionExperimento; runs: ExperimentRun[]; completedRuns: number; failedRuns: number; failureRate: number; statistics: Record<string, Record<string, Estadisticas>>; }
export interface ResultadoExperimento { experimentId: string; version: string; policyVersions: { policyId: string; policyVersion: string }[]; training: ResumenParticion; validation: ResumenParticion; holdout: ResumenParticion | null; pareto: string[]; weights?: Record<string, number>; evidence: string[]; failures: ExperimentRun[]; simulated: true; }
function unique(values: readonly (string | number)[]): boolean { return new Set(values).size === values.length; }
function overlap(a: readonly (string | number)[], b: readonly (string | number)[]): boolean { return a.some((x) => b.includes(x)); }
export function validarParticiones(c: ConfigExperimento): void { const groups = [c.trainingSeeds, c.validationSeeds, c.holdoutSeeds, c.trainingScenarios, c.validationScenarios, c.holdoutScenarios]; if (groups.some((g) => !unique(g))) throw new Error('Partición duplicada.'); if (c.strictPartitioning !== false && (overlap(c.trainingSeeds, c.validationSeeds) || overlap(c.trainingSeeds, c.holdoutSeeds) || overlap(c.validationSeeds, c.holdoutSeeds) || overlap(c.trainingScenarios, c.validationScenarios) || overlap(c.trainingScenarios, c.holdoutScenarios) || overlap(c.validationScenarios, c.holdoutScenarios))) throw new Error('Particiones solapadas.'); if (!c.policies.length || !Number.isInteger(c.duration) || c.duration < 0) throw new Error('Experimento inválido.'); if (c.weights && Object.values(c.weights).some((x) => !Number.isFinite(x))) throw new Error('Pesos inválidos.'); }
export function estadisticas(values: number[]): Estadisticas { if (!values.length) return { count: 0, mean: null, median: null, min: null, max: null, standardDeviation: null }; const sorted = [...values].sort((a, b) => a - b), mean = values.reduce((a, b) => a + b, 0) / values.length, middle = Math.floor(sorted.length / 2), median = sorted.length % 2 ? sorted[middle]! : (sorted[middle - 1]! + sorted[middle]!) / 2; return { count: values.length, mean, median, min: sorted[0]!, max: sorted.at(-1)!, standardDeviation: Math.sqrt(values.reduce((s, x) => s + (x - mean) ** 2, 0) / values.length) }; }
export function pareto(items: { id: string; metrics: MetricaExperimento[] }[]): string[] { return items.filter((a) => !items.some((b) => b !== a && a.metrics.every((m) => { const n = b.metrics.find((x) => x.name === m.name); return !!n && (m.direction === 'MAXIMIZE' ? n.value >= m.value : n.value <= m.value); }) && a.metrics.some((m) => { const n = b.metrics.find((x) => x.name === m.name)!; return m.direction === 'MAXIMIZE' ? n.value > m.value : n.value < m.value; }))).map((x) => x.id); }
function metricas(empresa: EmpresaSimulada): MetricaExperimento[] { const e = empresa.estado(); const stockouts = [...empresa.productos.values()].filter((p) => empresa.inventario(p.id).stockDisponible === 0).length; return [{ name: 'profit', value: e.utilidad, direction: 'MAXIMIZE' }, { name: 'margin', value: e.ventas ? e.utilidad / e.ventas : 0, direction: 'MAXIMIZE' }, { name: 'cash', value: e.caja, direction: 'MAXIMIZE' }, { name: 'cashDrawdown', value: 0, direction: 'MINIMIZE' }, { name: 'stockouts', value: stockouts, direction: 'MINIMIZE' }, { name: 'lostSales', value: 0, direction: 'MINIMIZE' }, { name: 'debt', value: e.cuentasPorPagar, direction: 'MINIMIZE' }, { name: 'ruleViolations', value: 0, direction: 'MINIMIZE' }, { name: 'incidents', value: 0, direction: 'MINIMIZE' }, { name: 'survival', value: e.caja >= 0 ? 1 : 0, direction: 'MAXIMIZE' }]; }
export class BusinessExperimentRunner {
  private completed = new Map<string, ExperimentRun>(); private state: EstadoExperimento = 'PENDING';
  private readonly memoria?: MemoriaEmpresarial;
  constructor(memoria?: MemoriaEmpresarial) { this.memoria = memoria; }
  status(): EstadoExperimento { return this.state; } pause(): void { if (this.state !== 'RUNNING') throw new Error('Transición inválida.'); this.state = 'PAUSED'; } resume(): void { if (this.state !== 'PAUSED') throw new Error('Transición inválida.'); this.state = 'RUNNING'; } stop(): void { if (!['PENDING', 'RUNNING', 'PAUSED'].includes(this.state)) throw new Error('Transición inválida.'); this.state = 'STOPPED'; }
  ejecutar(c: ConfigExperimento, includeHoldout = true): ResultadoExperimento { validarParticiones(c); if (this.state === 'STOPPED') throw new Error('Experimento detenido.'); this.state = 'RUNNING'; const training = this.particion(c, 'TRAINING', c.trainingSeeds, c.trainingScenarios); const validation = this.particion(c, 'VALIDATION', c.validationSeeds, c.validationScenarios); const holdout = includeHoldout ? this.particion(c, 'HOLDOUT', c.holdoutSeeds, c.holdoutScenarios) : null; const all = [...training.runs, ...validation.runs, ...(holdout?.runs ?? [])], ids = [...new Set(c.policies.map((p) => `${p.policyId}@${p.version}`))]; const aggregate = ids.map((id) => ({ id, metrics: all.filter((r) => `${r.policyId}@${r.policyVersion}` === id && r.status === 'COMPLETED').flatMap((r) => r.metrics).reduce<MetricaExperimento[]>((acc, m) => { const old = acc.find((x) => x.name === m.name); if (old) old.value += m.value; else acc.push({ ...m }); return acc; }, []) })); const result: ResultadoExperimento = { experimentId: c.experimentId, version: c.version, policyVersions: c.policies.map((p) => ({ policyId: p.policyId, policyVersion: p.version })), training, validation, holdout, pareto: pareto(aggregate), ...(c.weights ? { weights: { ...c.weights } } : {}), evidence: ['Resultados separados por partición; no existe ganador automático.'], failures: all.filter((r) => r.status === 'FAILED'), simulated: true }; this.guardarMemoria(c, result); this.state = 'COMPLETED'; return result; }
  private particion(c: ConfigExperimento, partition: ParticionExperimento, seeds: number[], scenarios: string[]): ResumenParticion { const runs: ExperimentRun[] = []; for (const seed of seeds) for (const scenario of scenarios) { const base = crearEmpresa({ ...c.configEmpresa, seed }); const checkpoint = base.snapshot(), checkpointId = `${c.experimentId}:${partition}:${seed}:${scenario}`; for (const policy of c.policies) { const key = `${checkpointId}:${policy.policyId}:${policy.version}`; let run = this.completed.get(key); if (!run) { try { const empresa = EmpresaSimulada.restaurar(checkpoint); for (let tick = 0; tick < c.duration; tick += 1) { const observation = observarEmpresa(empresa, scenario, `T${tick}`); const proposal = policy.propose(observation); if (proposal instanceof Promise) throw new Error('Policy asíncrona no soportada en experimento local.'); const result = procesarPropuesta(empresa, proposal, observation); if (result.result === 'REJECTED') throw new Error(result.reasonCode); } run = { experimentId: c.experimentId, partition, policyId: policy.policyId, policyVersion: policy.version, seed, scenario, initialCheckpointId: checkpointId, duration: c.duration, status: 'COMPLETED', metrics: metricas(empresa), violations: [], evaluation: 'SIMULATED', simulated: true }; } catch (error) { run = { experimentId: c.experimentId, partition, policyId: policy.policyId, policyVersion: policy.version, seed, scenario, initialCheckpointId: checkpointId, duration: c.duration, status: 'FAILED', metrics: [], violations: [], evaluation: 'FAILED', simulated: true, error: error instanceof Error ? error.message : 'fallo' }; } this.completed.set(key, run); } runs.push(run); } } const completed = runs.filter((r) => r.status === 'COMPLETED'), names = [...new Set(completed.flatMap((r) => r.metrics.map((m) => m.name)))], statistics = Object.fromEntries(c.policies.map((p) => [`${p.policyId}@${p.version}`, Object.fromEntries(names.map((n) => [n, estadisticas(completed.filter((r) => r.policyId === p.policyId && r.policyVersion === p.version).map((r) => r.metrics.find((m) => m.name === n)!.value))]))])); return { partition, runs, completedRuns: completed.length, failedRuns: runs.length - completed.length, failureRate: runs.length ? (runs.length - completed.length) / runs.length : 0, statistics }; }
  private guardarMemoria(c: ConfigExperimento, r: ResultadoExperimento): void { if (!this.memoria) return; for (const p of r.policyVersions) this.memoria.observar({ escenario: 'EXPERIMENT', seed: 0, contexto: JSON.stringify({ partition: 'VALIDATION', policy: p, simulated: true }), hipotesis: 'Evidencia agregada de experimento.', decision: `${p.policyId}@${p.policyVersion}`, metricasAntes: {}, metricasDespues: { completados: r.validation.completedRuns }, resultadoFinanciero: 0, reglasCumplidas: ['PARTITIONED'], reglasRotas: [], eventosExternos: [], evidencia: JSON.stringify({ pareto: r.pareto, failed: r.failures.length }), evaluacion: 'OBSERVADA: requiere evaluación central.', confianza: .5 }); }
}
