import { crearEmpresa, type EmpresaSimulada } from '../empresa-simulator/empresa.ts'; import type { ConfigEmpresa, EstadoEmpresa } from '../empresa-simulator/tipos.ts'; import { MemoriaEmpresarial } from '../empresa-simulator/memoria.ts';
export type EstadoCampana='PENDING'|'RUNNING'|'PAUSED'|'COMPLETED'|'FAILED'|'STOPPED'; export type EscenarioCampana='NORMAL'|'CRECIMIENTO_RAPIDO'|'CAIDA_DEMANDA'|'CRISIS_CAJA'|'AUMENTO_COSTES'|'ROTURA_STOCK'|'PROVEEDOR_RETRASADO'|'CRECIMIENTO_ESTACIONAL';
export type Decision={tipo:'ComprarInventario'|'ReservarInventario'|'MantenerEstado'; productoId?:string; cantidad?:number; motivo:string}; export interface BusinessPolicy { version:string; observe(e:EmpresaSimulada):Readonly<EstadoEmpresa>; propose(o:Readonly<EstadoEmpresa>,e:EmpresaSimulada):Decision; explain(d:Decision):string; }
export class BaselineBusinessPolicy implements BusinessPolicy { version='baseline-v1'; observe(e:EmpresaSimulada){return Object.freeze(e.estado())} propose(_o:Readonly<EstadoEmpresa>,e:EmpresaSimulada):Decision{const p=[...e.productos.values()][0]!; return e.inventario(p.id).stockDisponible<p.stockMinimo?{tipo:'ComprarInventario',productoId:p.id,cantidad:p.stockMinimo*2,motivo:'stock disponible bajo mínimo'}:{tipo:'MantenerEstado',motivo:'estado dentro de límites'}} explain(d:Decision){return d.motivo} }
export interface BusinessCampaign { campaignId:string; nombre:string; version:string; scenarioSet:EscenarioCampana[]; seedSet:number[]; policy:BusinessPolicy; duracionVirtual:number; configEmpresa:ConfigEmpresa; metricasObjetivo:string[]; createdAt:string; status:EstadoCampana; }
export interface BusinessRun { runId:string; campaignId:string; seed:number; scenario:EscenarioCampana; policyVersion:string; atlasVersion:string; startState:EstadoEmpresa; endState:EstadoEmpresa; decisions:Decision[]; events:string[]; metrics:Record<string,number|boolean>; status:EstadoCampana; error?:string; }
export class BusinessCampaignRunner { private runs=new Map<string,BusinessRun>(); ejecutar(c:BusinessCampaign):BusinessRun[]{if(c.status==='COMPLETED')return this.resultados(c.campaignId);if(!['PENDING','PAUSED'].includes(c.status))throw new Error('Campaña no ejecutable.'); c.status='RUNNING'; for(const seed of c.seedSet)for(const scenario of c.scenarioSet){const id=`${c.campaignId}:${seed}:${scenario}`;if(this.runs.has(id))continue; try{const e=crearEmpresa({...c.configEmpresa,seed});const inicio=e.estado(),decisiones:Decision[]=[];for(let dia=0;dia<c.duracionVirtual;dia+=1){const d=c.policy.propose(c.policy.observe(e),e);decisiones.push(d);if(d.tipo==='ComprarInventario')e.comprar(d.productoId!,d.cantidad!,undefined,true,`${id}:compra:${dia}`)}const fin=e.estado();this.runs.set(id,{runId:id,campaignId:c.campaignId,seed,scenario,policyVersion:c.policy.version,atlasVersion:'0.1.0',startState:inicio,endState:fin,decisions:decisiones,events:[],metrics:{ingresos:fin.ventas,costes:fin.costos,beneficio:fin.utilidad,caja:fin.caja,inventario:fin.inventarioValorizado,cuentasCobrar:fin.cuentasPorCobrar,cuentasPagar:fin.cuentasPorPagar,simulated:true},status:'COMPLETED'})}catch(error){this.runs.set(id,{runId:id,campaignId:c.campaignId,seed,scenario,policyVersion:c.policy.version,atlasVersion:'0.1.0',startState:{} as EstadoEmpresa,endState:{} as EstadoEmpresa,decisions:[],events:[],metrics:{simulated:true},status:'FAILED',error:error instanceof Error?error.message:'fallo'})}} c.status='COMPLETED';return this.resultados(c.campaignId)} resultados(id:string){return [...this.runs.values()].filter(r=>r.campaignId===id)} resultado(id:string){const r=this.resultados(id),beneficios=r.map(x=>Number(x.metrics.beneficio??0));return {runs:r.length,completados:r.filter(x=>x.status==='COMPLETED').length,fallidos:r.filter(x=>x.status==='FAILED').length,beneficioMedio:beneficios.reduce((a,b)=>a+b,0)/(beneficios.length||1),simulated:true}} }
export class BusinessExperiment { comparar(policies:BusinessPolicy[], base:Omit<BusinessCampaign,'policy'|'campaignId'|'status'|'createdAt'>){return policies.map((policy,i)=>{const c:BusinessCampaign={...base,campaignId:`exp-${i}`,policy,status:'PENDING',createdAt:'simulado'};const runner=new BusinessCampaignRunner();runner.ejecutar(c);return {policy:policy.version,result:runner.resultado(c.campaignId),holdout:false}})} }
export class BusinessAgentLoop { private memoria:MemoriaEmpresarial; constructor(memoria:MemoriaEmpresarial){this.memoria=memoria} ejecutar(e:EmpresaSimulada,policy:BusinessPolicy,ticks:number){for(let i=0;i<ticks;i+=1){const d=policy.propose(policy.observe(e),e);if(d.tipo==='ComprarInventario')e.comprar(d.productoId!,d.cantidad!,undefined,true,`loop:${i}`)} return e.estado()} }
