import type { CuentaMT5, EstadoMT5, HistorialMT5, MT5ReadOnlyBridge, PeticionBridge, PosicionMT5, SimboloMT5, TickMT5, TransporteBridge, VelaMT5 } from './tipos.ts';
export class BridgeMT5Error extends Error {}
export class BridgeMT5Timeout extends BridgeMT5Error {}
export class BridgeMT5Seguridad extends BridgeMT5Error {}
export interface PoliticaBridge { tradingMode: string | undefined; realTrading: string | undefined; timeoutMs: number; }
export const politicaDesdeEntorno = (): PoliticaBridge => ({ tradingMode: process.env.TRADING_MODE, realTrading: process.env.REAL_TRADING, timeoutMs: 1_000 });
function asegurarPuerta(p: PoliticaBridge): void { if (p.tradingMode !== 'DEMO_ONLY' || p.realTrading !== 'false') throw new BridgeMT5Seguridad('Bridge MT5 bloqueado: exige DEMO_ONLY y REAL_TRADING=false.'); }
function texto(v: unknown, campo: string): string { if (typeof v !== 'string' || !v) throw new BridgeMT5Error(`Dato MT5 inválido: ${campo}.`); return v; }
function numero(v: unknown, campo: string, cero = false): number { if (typeof v !== 'number' || !Number.isFinite(v) || (cero ? v < 0 : v <= 0)) throw new BridgeMT5Error(`Dato MT5 inválido: ${campo}.`); return v; }
function objeto(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) throw new BridgeMT5Error('Respuesta MT5 inválida.'); return v as Record<string, unknown>; }
function fecha(v: unknown, campo: string): string { const r = texto(v, campo); if (!Number.isFinite(Date.parse(r))) throw new BridgeMT5Error(`Dato MT5 inválido: ${campo}.`); return r; }
function cuenta(v: unknown): CuentaMT5 { const r = objeto(v); const tipo = texto(r.tipo, 'tipo'); if (tipo !== 'DEMO' && tipo !== 'DEMO_CENTS' && tipo !== 'DEMO_FIXED') throw new BridgeMT5Seguridad(`Cuenta MT5 bloqueada: tipo '${tipo}' no permitido (solo DEMO). MT5 REAL está completamente deshabilitado.`); return { tipo: tipo as 'DEMO' | 'DEMO_CENTS' | 'DEMO_FIXED', idSeguro: texto(r.idSeguro, 'idSeguro'), moneda: texto(r.moneda, 'moneda'), apalancamiento: numero(r.apalancamiento, 'apalancamiento') }; }
function tick(v: unknown): TickMT5 { const r = objeto(v); const bid = numero(r.bid, 'bid'), ask = numero(r.ask, 'ask'); if (ask < bid) throw new BridgeMT5Error('Dato MT5 inválido: spread negativo.'); return { simbolo: texto(r.simbolo, 'simbolo'), fecha: fecha(r.fecha, 'fecha'), bid, ask }; }
function vela(v: unknown): VelaMT5 { const r = objeto(v); const apertura = numero(r.apertura, 'apertura'), maximo = numero(r.maximo, 'maximo'), minimo = numero(r.minimo, 'minimo'), cierre = numero(r.cierre, 'cierre'); if (maximo < Math.max(apertura, cierre) || minimo > Math.min(apertura, cierre)) throw new BridgeMT5Error('Vela MT5 inválida.'); return { fecha: fecha(r.fecha, 'fecha'), apertura, maximo, minimo, cierre, volumen: numero(r.volumen, 'volumen', true) }; }
function lista<T>(v: unknown, convertir: (x: unknown) => T): T[] { if (!Array.isArray(v)) throw new BridgeMT5Error('Lista MT5 inválida.'); return v.map(convertir); }
export class ClienteMT5SoloLectura implements MT5ReadOnlyBridge {
  private readonly transporte: TransporteBridge;
  private readonly politica: PoliticaBridge;
  constructor(transporte: TransporteBridge, politica: PoliticaBridge = politicaDesdeEntorno()) { this.transporte = transporte; this.politica = politica; asegurarPuerta(politica); }
  private async pedir(peticion: PeticionBridge): Promise<unknown> { asegurarPuerta(this.politica); for (let intento = 0; intento < 2; intento += 1) { try { return await Promise.race([this.transporte.solicitar(peticion), new Promise<never>((_, rechazar) => setTimeout(() => rechazar(new BridgeMT5Timeout('Timeout seguro del bridge MT5.')), this.politica.timeoutMs))]); } catch (error) { if (error instanceof BridgeMT5Timeout) throw error; if (intento === 1) throw new BridgeMT5Error('Bridge MT5 desconectado o no disponible.'); } } throw new BridgeMT5Error('Bridge MT5 no disponible.'); }
  async estado(): Promise<EstadoMT5> { const r = objeto(await this.pedir({ operacion: 'estado' })); if (typeof r.conectado !== 'boolean' || (r.terminal !== 'disponible' && r.terminal !== 'desconectado')) throw new BridgeMT5Error('Estado MT5 inválido.'); return { conectado: r.conectado, terminal: r.terminal, servidor: r.servidor === null ? null : texto(r.servidor, 'servidor') }; }
  async cuenta(): Promise<CuentaMT5> { return cuenta(await this.pedir({ operacion: 'cuenta' })); }
  async simbolos(): Promise<SimboloMT5[]> { return lista(await this.pedir({ operacion: 'simbolos' }), (v) => { const r = objeto(v); return { nombre: texto(r.nombre, 'nombre'), digitos: numero(r.digitos, 'digitos', true) }; }); }
  async tick(simbolo: string): Promise<TickMT5> { return tick(await this.pedir({ operacion: 'tick', simbolo: texto(simbolo, 'simbolo') })); }
  async velas(simbolo: string, desde: string, hasta: string, limite: number): Promise<VelaMT5[]> { if (!Number.isInteger(limite) || limite < 1 || limite > 10_000 || !Number.isFinite(Date.parse(desde)) || !Number.isFinite(Date.parse(hasta))) throw new BridgeMT5Error('Petición de velas inválida.'); return lista(await this.pedir({ operacion: 'velas', simbolo, desde, hasta, limite }), vela); }
  async posiciones(): Promise<PosicionMT5[]> { return lista(await this.pedir({ operacion: 'posiciones' }), (v) => { const r = objeto(v); if (r.lado !== 'compra' && r.lado !== 'venta') throw new BridgeMT5Error('Posición MT5 inválida.'); return { ticketSeguro: texto(r.ticketSeguro, 'ticketSeguro'), simbolo: texto(r.simbolo, 'simbolo'), lado: r.lado, volumen: numero(r.volumen, 'volumen'), precioApertura: numero(r.precioApertura, 'precioApertura') }; }); }
  async historial(desde: string, hasta: string, limite: number): Promise<HistorialMT5[]> { if (!Number.isInteger(limite) || limite < 1 || limite > 10_000 || !Number.isFinite(Date.parse(desde)) || !Number.isFinite(Date.parse(hasta))) throw new BridgeMT5Error('Petición de historial inválida.'); return lista(await this.pedir({ operacion: 'historial', desde, hasta, limite }), (v) => { const r = objeto(v); return { idSeguro: texto(r.idSeguro, 'idSeguro'), simbolo: texto(r.simbolo, 'simbolo'), fecha: fecha(r.fecha, 'fecha'), resultado: numero(r.resultado, 'resultado', true) }; }); }
}
