import { validarSerieHistorica } from './datos.ts';
import { crearCruceMedias, senalCruceMedias } from './estrategias.ts';
import type { ConfiguracionBacktest, EstrategiaDeclarativa, MetricasBacktest, OperacionBacktest, ResultadoBacktest, SerieHistorica, Senal } from './tipos.ts';
export class ConfiguracionBacktestInvalida extends Error {}
const redondear = (valor: number) => Math.round((valor + Number.EPSILON) * 1e8) / 1e8;
function validarConfiguracion(c: ConfiguracionBacktest): void { if (!Number.isFinite(c.capitalInicial) || c.capitalInicial <= 0 || ![c.comisionPorcentaje, c.spreadPorcentaje, c.slippagePorcentaje, c.maxRiesgoPorOperacion].every((v) => Number.isFinite(v) && v >= 0 && v <= 1) || !Number.isInteger(c.semilla)) throw new ConfiguracionBacktestInvalida('Configuración de backtest inválida.'); }
function ejecucion(precio: number, lado: 'compra' | 'venta', c: ConfiguracionBacktest): number { const friccion = c.spreadPorcentaje / 2 + c.slippagePorcentaje; return precio * (lado === 'compra' ? 1 + friccion : 1 - friccion); }
/** Motor long-only determinista. No tiene conectores, órdenes ni efectos fuera de memoria. */
export function ejecutarBacktest(serie: SerieHistorica, entrada: EstrategiaDeclarativa, c: ConfiguracionBacktest): ResultadoBacktest {
  validarSerieHistorica(serie); validarConfiguracion(c); const estrategia = crearCruceMedias(entrada); const reglasVioladas = estrategia.riesgoPorOperacion > c.maxRiesgoPorOperacion ? ['riesgo_por_operacion_excedido'] : [];
  const benchmark = redondear((serie.velas.at(-1)!.cierre / serie.velas[0]!.apertura - 1) * 100); const vacias: MetricasBacktest = { operaciones: 0, retornoNeto: 0, profitFactor: null, drawdownMaximo: 0, ratioRiesgoBeneficio: null, exposicion: 0, comisiones: 0, benchmarkRetorno: benchmark };
  const base = { reproducible: true as const, estrategia: { id: estrategia.id, version: estrategia.version, tipo: estrategia.tipo }, datos: { id: serie.id, simbolo: serie.simbolo, intervalo: serie.intervalo, origen: serie.origen, velas: serie.velas.length }, semilla: c.semilla };
  if (reglasVioladas.length) return { ...base, aprobado: false, reglasVioladas, operaciones: [], metricas: vacias };
  let efectivo = c.capitalInicial, cantidad = 0, precioEntrada = 0, fechaEntrada = '', comisionEntrada = 0, maxCapital = efectivo, dd = 0, expuestas = 0, comisiones = 0; let pendiente: Senal = 'mantener'; const operaciones: OperacionBacktest[] = []; const ganancias: number[] = []; const perdidas: number[] = [];
  const cerrar = (fecha: string, precioBase: number) => { const precio = ejecucion(precioBase, 'venta', c), bruto = cantidad * precio, salida = bruto * c.comisionPorcentaje, pnl = bruto - salida - (cantidad * precioEntrada + comisionEntrada); efectivo += bruto - salida; comisiones += salida; operaciones.push({ entrada: fechaEntrada, salida: fecha, precioEntrada: redondear(precioEntrada), precioSalida: redondear(precio), cantidad: redondear(cantidad), pnlNeto: redondear(pnl), comisiones: redondear(comisionEntrada + salida) }); (pnl >= 0 ? ganancias : perdidas).push(pnl); cantidad = 0; comisionEntrada = 0; };
  for (let i = 1; i < serie.velas.length; i += 1) { const vela = serie.velas[i]!; if (pendiente === 'comprar' && cantidad === 0) { const precio = ejecucion(vela.apertura, 'compra', c), gasto = efectivo / (1 + c.comisionPorcentaje); cantidad = gasto / precio; comisionEntrada = gasto * c.comisionPorcentaje; efectivo -= gasto + comisionEntrada; precioEntrada = precio; fechaEntrada = vela.fecha; comisiones += comisionEntrada; } else if (pendiente === 'vender' && cantidad > 0) cerrar(vela.fecha, vela.apertura); if (cantidad > 0) expuestas += 1; const marcado = efectivo + cantidad * vela.cierre; maxCapital = Math.max(maxCapital, marcado); dd = Math.max(dd, (maxCapital - marcado) / maxCapital * 100); pendiente = senalCruceMedias(estrategia, serie.velas, i); }
  if (cantidad > 0) { const ultima = serie.velas.at(-1)!; cerrar(ultima.fecha, ultima.cierre); }
  const totalGanancias = ganancias.reduce((a, b) => a + b, 0), totalPerdidas = perdidas.reduce((a, b) => a + Math.abs(b), 0), ratio = totalPerdidas ? redondear(totalGanancias / totalPerdidas) : null;
  const metricas: MetricasBacktest = { operaciones: operaciones.length, retornoNeto: redondear((efectivo / c.capitalInicial - 1) * 100), profitFactor: ratio, drawdownMaximo: redondear(dd), ratioRiesgoBeneficio: ratio, exposicion: redondear(expuestas / (serie.velas.length - 1) * 100), comisiones: redondear(comisiones), benchmarkRetorno: benchmark };
  return { ...base, aprobado: true, reglasVioladas: [], operaciones, metricas };
}
