import { ejecutarBacktest, ConfiguracionBacktestInvalida } from './backtest.ts'; import { EstrategiaInvalida } from './estrategias.ts'; import { crearExperimentoDesdeBacktest, obtenerRepositorio } from './experimentos.ts'; import type { ConfiguracionBacktest, EstrategiaDeclarativa, ResultadoBacktest, SerieHistorica } from './tipos.ts'; import type { FuenteMT5DEMO } from './mt5-datasource.ts';
import { evaluateChallenge } from './challenge-simulator.ts';
import { createTestFixturePropFirm } from './prop-firm.ts';
const velasDesde = (mes: string, filas: number[][], volumen: number): SerieHistorica['velas'] => filas.map(([apertura, maximo, minimo, cierre], i) => ({ fecha: `2025-${mes}-${String(i + 1).padStart(2, '0')}T00:00:00.000Z`, apertura: apertura!, maximo: maximo!, minimo: minimo!, cierre: cierre!, volumen }));
export const SERIE_PANEL: SerieHistorica = { id: 'ficticia-btc-1d-v1', simbolo: 'BTC-USD-FICTICIO', intervalo: '1d', origen: 'fixture-local', velas: velasDesde('01', [[100,101,99,100],[99,100,98,99],[98,100,97,99],[100,103,99,102],[103,106,102,105],[104,105,100,101],[100,101,96,97],[96,98,95,97]], 10) };
/** Segundo fixture Forex; misma matemática long-only del motor, precios de par de divisas. */
export const SERIE_FOREX: SerieHistorica = { id: 'ficticia-eurusd-1d-v1', simbolo: 'EUR/USD-FICTICIO', intervalo: '1d', origen: 'fixture-local', velas: velasDesde('02', [[1.0800,1.0810,1.0790,1.0800],[1.0800,1.0805,1.0785,1.0790],[1.0790,1.0800,1.0780,1.0785],[1.0785,1.0830,1.0784,1.0820],[1.0820,1.0860,1.0815,1.0850],[1.0850,1.0855,1.0820,1.0830],[1.0830,1.0835,1.0790,1.0795],[1.0795,1.0800,1.0770,1.0780]], 1000) };
export const ESTRATEGIA_PANEL: EstrategiaDeclarativa = { tipo: 'cruce_medias', id: 'cruce-demo', version: 1, mediaRapida: 2, mediaLenta: 3, riesgoPorOperacion: .01 };
/** Registro cerrado de instrumentos simulados; la UI y el motor sólo ven lo declarado aquí. */
const INSTRUMENTOS: readonly { serie: SerieHistorica; claseActivo: 'CRYPTO' | 'FX' }[] = [{ serie: SERIE_PANEL, claseActivo: 'CRYPTO' }, { serie: SERIE_FOREX, claseActivo: 'FX' }];
let fuenteMT5: FuenteMT5DEMO | null = null;
export function asignarFuenteMT5(fuente: FuenteMT5DEMO | null) { fuenteMT5 = fuente; }
let repositorioExperimentos: any = null;
export function asignarRepositorioExperimentos(repo: any) { repositorioExperimentos = repo; }
const redondear = (valor: number) => Math.round((valor + Number.EPSILON) * 1e8) / 1e8;
export async function catalogoBacktestPanel(incluirMT5 = false){ const instrumentos = INSTRUMENTOS.map(({ serie, claseActivo }) => ({ id: serie.id, simbolo: serie.simbolo, intervalo: serie.intervalo, origen: serie.origen, claseActivo, etiqueta: 'SIMULATED / FIXTURE', desde: serie.velas[0]!.fecha, hasta: serie.velas.at(-1)!.fecha, ohlc: true, velas: serie.velas.map((v) => ({ fecha: v.fecha, apertura: v.apertura, maximo: v.maximo, minimo: v.minimo, cierre: v.cierre, volumen: v.volumen })) })); if (incluirMT5 && fuenteMT5?.conectado()) { const mt5Simbolos = await fuenteMT5.simbolosDisponibles(); for (const s of mt5Simbolos) { const serie = await fuenteMT5.obtenerSerie(s, '2025-01-01', '2099-12-31'); if (serie) { instrumentos.push({ id: serie.id, simbolo: s, intervalo: '1d', origen: 'mt5-demo', claseActivo: 'FX' as const, etiqueta: 'MT5 / DEMO / READ-ONLY', desde: serie.velas[0]?.fecha || '2025-01-01T00:00:00.000Z', hasta: serie.velas.at(-1)?.fecha || '2025-12-31T23:59:59.999Z', ohlc: true, velas: serie.velas }); } } } return { simulated: true, instrumentos, estrategias: [{ id: ESTRATEGIA_PANEL.id, tipo: ESTRATEGIA_PANEL.tipo, version: ESTRATEGIA_PANEL.version, parametros: ['mediaRapida','mediaLenta','riesgoPorOperacion'] }] }; }
/** Recorta la serie real por rango de fechas; nunca fabrica velas ni acepta fechas fuera del histórico. */
function subserie(base: SerieHistorica, desde: unknown, hasta: unknown): SerieHistorica {
  if (desde === undefined && hasta === undefined) return base;
  if (typeof desde !== 'string' || typeof hasta !== 'string') throw new ConfiguracionBacktestInvalida('Rango de fechas inválido.');
  const inicio = Date.parse(desde), fin = Date.parse(hasta);
  const min = Date.parse(base.velas[0]!.fecha), max = Date.parse(base.velas.at(-1)!.fecha);
  if (!Number.isFinite(inicio) || !Number.isFinite(fin) || inicio > fin || inicio < min || fin > max) throw new ConfiguracionBacktestInvalida('Rango de fechas fuera del histórico.');
  const velas = base.velas.filter((v) => { const t = Date.parse(v.fecha); return t >= inicio && t <= fin; });
  return { ...base, id: `${base.id}:rango`, velas };
}
/** Deriva únicamente magnitudes reales del resultado del motor; una sola fuente para UI y pruebas. */
export function resumenBacktest(capitalInicial: number, resultado: ResultadoBacktest){
  const m = resultado.metricas, ops = resultado.operaciones;
  const finalEquity = redondear(capitalInicial * (1 + m.retornoNeto / 100));
  const wins = ops.filter((o) => o.pnlNeto >= 0).length, losses = ops.filter((o) => o.pnlNeto < 0).length;
  const comisionesOperaciones = redondear(ops.reduce((s, o) => s + o.comisiones, 0));
  return { capitalInicial, finalEquity, netPnl: redondear(finalEquity - capitalInicial), retorno: m.retornoNeto, maxDrawdown: m.drawdownMaximo, operaciones: ops.length, wins, losses, winRate: ops.length ? redondear(wins / ops.length * 100) : null, profitFactor: m.profitFactor, comisiones: m.comisiones, comisionesOperaciones };
}
export async function ejecutarBacktestPanel(entrada: Record<string, unknown>){ let serie: SerieHistorica | undefined; let claseActivo: 'CRYPTO' | 'FX' = 'FX'; const registro = INSTRUMENTOS.find((x) => x.serie.id === entrada.instrumento); if (registro) { serie = subserie(registro.serie, entrada.desde, entrada.hasta); claseActivo = registro.claseActivo; } else if (entrada.instrumento && String(entrada.instrumento).startsWith('mt5-demo-') && fuenteMT5?.conectado()) { const simbolo = String(entrada.instrumento).replace('mt5-demo-', ''); const desde = typeof entrada.desde === 'string' ? entrada.desde : '2025-01-01'; const hasta = typeof entrada.hasta === 'string' ? entrada.hasta : '2099-12-31'; serie = await fuenteMT5.obtenerSerie(simbolo, desde, hasta) ?? undefined; } if (!serie || entrada.estrategia !== ESTRATEGIA_PANEL.id) throw new Error('BACKTEST_SELECTION_INVALID'); const capital = entrada.capitalInicial, comision = entrada.comisionPorcentaje; if (typeof capital !== 'number' || !Number.isFinite(capital) || capital <= 0 || capital > 10_000_000 || typeof comision !== 'number' || !Number.isFinite(comision) || comision < 0 || comision > .1) throw new ConfiguracionBacktestInvalida('Configuración de panel inválida.'); const config: ConfiguracionBacktest = { capitalInicial: capital, comisionPorcentaje: comision, spreadPorcentaje: .002, slippagePorcentaje: .001, maxRiesgoPorOperacion: .02, semilla: 7 }; const resultado = ejecutarBacktest(serie, ESTRATEGIA_PANEL, config); const experimento = crearExperimentoDesdeBacktest(serie, ESTRATEGIA_PANEL, resultado, capital, comision); (repositorioExperimentos || obtenerRepositorio()).guardarExperimento(experimento); const prog = createTestFixturePropFirm().programs[0]!; const challenge = evaluateChallenge(resultado, prog, claseActivo === 'CRYPTO' ? 'CRYPTO' : 'FOREX_SPOT', serie.simbolo, { backtestInitialCapital: capital }); return { simulated: true, estado: 'COMPLETED', instrumento: String(entrada.instrumento), simbolo: serie.simbolo, claseActivo, capitalInicial: capital, periodo: { desde: serie.velas[0]!.fecha, hasta: serie.velas.at(-1)!.fecha }, velas: serie.velas.map((v) => ({ fecha: v.fecha, apertura: v.apertura, maximo: v.maximo, minimo: v.minimo, cierre: v.cierre })), resumen: resumenBacktest(capital, resultado), resultado, runId: experimento.runId, challenge }; }
export { ConfiguracionBacktestInvalida, EstrategiaInvalida };
