import { ejecutarBacktest } from './backtest.ts';
import { validarSerieHistorica } from './datos.ts';
import type { ConfiguracionBacktest, EstrategiaDeclarativa, ResultadoBacktest, SerieHistorica } from './tipos.ts';
export class DivisionInvalida extends Error {}
export interface FueraMuestra { entrenamiento: ResultadoBacktest; validacion: ResultadoBacktest; inicioValidacion: string; }
export interface VentanaWalkForward { entrenamiento: ResultadoBacktest; validacion: ResultadoBacktest; inicioEntrenamiento: string; inicioValidacion: string; }
function fragmento(serie: SerieHistorica, desde: number, hasta: number, sufijo: string): SerieHistorica { return { ...serie, id: `${serie.id}:${sufijo}`, velas: serie.velas.slice(desde, hasta) }; }
/** Separa períodos contiguos; fuera de muestra nunca llega al entrenamiento. */
export function validarFueraMuestra(serie: SerieHistorica, estrategia: EstrategiaDeclarativa, configuracion: ConfiguracionBacktest, velasEntrenamiento: number): FueraMuestra { validarSerieHistorica(serie); if (!Number.isInteger(velasEntrenamiento) || velasEntrenamiento < estrategia.mediaLenta + 2 || velasEntrenamiento > serie.velas.length - 2) throw new DivisionInvalida('División entrenamiento/fuera de muestra inválida.'); const entrenamiento = fragmento(serie, 0, velasEntrenamiento, 'entrenamiento'), validacion = fragmento(serie, velasEntrenamiento, serie.velas.length, 'fuera-muestra'); return { entrenamiento: ejecutarBacktest(entrenamiento, estrategia, configuracion), validacion: ejecutarBacktest(validacion, estrategia, configuracion), inicioValidacion: validacion.velas[0]!.fecha }; }
/** Repite ventanas sin adaptar parámetros durante su validación. */
export function ejecutarWalkForward(serie: SerieHistorica, estrategia: EstrategiaDeclarativa, configuracion: ConfiguracionBacktest, velasEntrenamiento: number, velasValidacion: number): VentanaWalkForward[] { validarSerieHistorica(serie); if (!Number.isInteger(velasEntrenamiento) || !Number.isInteger(velasValidacion) || velasEntrenamiento < estrategia.mediaLenta + 1 || velasValidacion < 2) throw new DivisionInvalida('Ventanas walk-forward inválidas.'); const resultado: VentanaWalkForward[] = []; for (let inicio = 0; inicio + velasEntrenamiento + velasValidacion <= serie.velas.length; inicio += velasValidacion) { const entrenamiento = fragmento(serie, inicio, inicio + velasEntrenamiento, `wf-${inicio}-entrenamiento`), validacion = fragmento(serie, inicio + velasEntrenamiento, inicio + velasEntrenamiento + velasValidacion, `wf-${inicio}-validacion`); resultado.push({ entrenamiento: ejecutarBacktest(entrenamiento, estrategia, configuracion), validacion: ejecutarBacktest(validacion, estrategia, configuracion), inicioEntrenamiento: entrenamiento.velas[0]!.fecha, inicioValidacion: validacion.velas[0]!.fecha }); } if (!resultado.length) throw new DivisionInvalida('No cabe una ventana walk-forward completa.'); return resultado; }
